# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

plugins: [jekyll-paginate]
paginate_path: "page:num"

# Setup
title:               Shaǵala Lab blogı
tagline:             'bagdarlamalastırıw haqqında blog'
description:         '<a href="http://shagalalab.com">Shaǵala Lab</a> toparınıń bagdarlamalastırıw haqqında blogı'
url:                 http://shagalalab.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shaǵala Lab
  url:               http://shagalalab.com
  email:             info@shagalalab.com

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/shagalalab/shagalalab.github.io